# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: pfe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yassine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DATABASE_URL=postgresql://postgres:yassine@db:5432/pfe
      - SPARQL_ENDPOINT=${SPARQL_ENDPOINT:-http://graphdb:7200/repositories/mon_repo}
    depends_on:
      - db
    volumes:
      - ./media:/app/media

  graphdb:
    image: ontotext/graphdb:10.0.0
    ports:
      - "7200:7200"
    volumes:
      - graphdb_data:/opt/graphdb/home

volumes:
  postgres_data:
  graphdb_data: