# Generated by Django 5.2.4 on 2026-05-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_utilisateur_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='photoProfil',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
