# Generated by Codex on 2026-02-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_add_date_naissance_photo_profil"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="estSupprime",
            field=models.BooleanField(default=False),
        ),
    ]
