# Generated by Codex on 2026-03-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_cv_estsupprime"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="ai_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cv",
            name="ai_has_photo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cv",
            name="ai_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="cv",
            name="ai_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cv",
            name="ai_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("validated", "Validated"), ("rejected", "Rejected")],
                default="pending",
                max_length=20,
            ),
        ),
    ]
