# Generated by Django 5.2.4 on 2026-05-06 03:39

import cloudinary_storage.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_cv_fichier_alter_utilisateur_photoprofil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='fichier',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='photoProfil',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=''),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notificationId', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('rendez_vous', 'Rendez-vous'), ('candidature', 'Candidature'), ('system', 'Système')], default='system', max_length=20)),
                ('lu', models.BooleanField(default=False)),
                ('lien', models.CharField(blank=True, max_length=255, null=True)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dateCreation'],
                'indexes': [models.Index(fields=['utilisateur', 'lu', 'dateCreation'], name='main_notifi_utilisa_7be127_idx')],
            },
        ),
    ]
