# Generated by Codex on 2026-03-03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_cv_ai_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EntretienCreneau",
            fields=[
                ("creneauId", models.AutoField(primary_key=True, serialize=False)),
                ("startAt", models.DateTimeField()),
                ("endAt", models.DateTimeField()),
                ("mode", models.CharField(choices=[("visio", "Visio"), ("site", "Sur site")], default="visio", max_length=20)),
                ("lieuOuLien", models.CharField(blank=True, default="", max_length=255)),
                ("note", models.TextField(blank=True, default="")),
                ("estReserve", models.BooleanField(default=False)),
                ("dateReservation", models.DateTimeField(blank=True, null=True)),
                ("dateCreation", models.DateTimeField(auto_now_add=True)),
                ("envoi", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="creneaux", to="main.envoi")),
                ("reservePar", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="entretiens_reserves", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name="entretiencreneau",
            index=models.Index(fields=["startAt"], name="main_entret_startAt_c47f9f_idx"),
        ),
        migrations.AddIndex(
            model_name="entretiencreneau",
            index=models.Index(fields=["estReserve"], name="main_entret_estRese_5f3ad8_idx"),
        ),
        migrations.AddIndex(
            model_name="entretiencreneau",
            index=models.Index(fields=["envoi", "startAt"], name="main_entret_envoi_i_2e4ea3_idx"),
        ),
    ]
