# Generated by Django 5.2.4 on 2026-04-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_entretiencreneau'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='offre',
            name='main_offre_estPubl_295eab_idx',
        ),
        
        
        migrations.AddIndex(
            model_name='offre',
            index=models.Index(fields=['recevoirCandidatures', 'estArchivee'], name='main_offre_recevoi_db8759_idx'),
        ),
    ]
