# Generated by Django 5.2.4 on 2026-04-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_entretiencreneau'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='offre',
            name='main_offre_estPubl_295eab_idx',
        ),
        migrations.RenameIndex(
            model_name='entretiencreneau',
            new_name='main_entret_startAt_81a236_idx',
            old_name='main_entret_startAt_c47f9f_idx',
        ),
        migrations.RenameIndex(
            model_name='entretiencreneau',
            new_name='main_entret_estRese_23b30e_idx',
            old_name='main_entret_estRese_5f3ad8_idx',
        ),
        migrations.RenameIndex(
            model_name='entretiencreneau',
            new_name='main_entret_envoi_i_cf18ca_idx',
            old_name='main_entret_envoi_i_2e4ea3_idx',
        ),
        migrations.RemoveField(
            model_name='offre',
            name='estPubliee',
        ),
        migrations.AddIndex(
            model_name='offre',
            index=models.Index(fields=['recevoirCandidatures', 'estArchivee'], name='main_offre_recevoi_db8759_idx'),
        ),
    ]
